name: gdrm_sdk
description: "Enterprise DRM & Hardware-Locked Secure PDF & GDRM Document Viewer SDK with Dynamic Forensic Watermarking."
version: 1.0.0
homepage: https://github.com/Gauruuu/GDRM
repository: https://github.com/Gauruuu/GDRM/tree/main/packages/gdrm_sdk
issue_tracker: https://github.com/Gauruuu/GDRM/issues

topics:
  - drm
  - pdf
  - security
  - watermark
  - document-viewer

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  syncfusion_flutter_pdfviewer: ^27.0.0
  intl: ^0.19.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
