// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvgrHhpaPUqlcG6j87cUar__0G5-3aAj0',
    appId: '1:936537359592:web:00991e47c0be999515355d',
    messagingSenderId: '936537359592',
    projectId: 'gdrm-userbase',
    authDomain: 'gdrm-userbase.firebaseapp.com',
    storageBucket: 'gdrm-userbase.firebasestorage.app',
    measurementId: 'G-CBHLQ97STQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCw328YsMnQigv6xxk8n0ED9VcT-IfDoY',
    appId: '1:936537359592:android:b1663ac4b110f78515355d',
    messagingSenderId: '936537359592',
    projectId: 'gdrm-userbase',
    storageBucket: 'gdrm-userbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnns4zbhnaILo3BPZl4PcVfiHx07-uOxk',
    appId: '1:936537359592:ios:ae58427e750f094315355d',
    messagingSenderId: '936537359592',
    projectId: 'gdrm-userbase',
    storageBucket: 'gdrm-userbase.firebasestorage.app',
    iosBundleId: 'com.hlp.gdrmEcosystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnns4zbhnaILo3BPZl4PcVfiHx07-uOxk',
    appId: '1:936537359592:ios:ae58427e750f094315355d',
    messagingSenderId: '936537359592',
    projectId: 'gdrm-userbase',
    storageBucket: 'gdrm-userbase.firebasestorage.app',
    iosBundleId: 'com.hlp.gdrmEcosystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvgrHhpaPUqlcG6j87cUar__0G5-3aAj0',
    appId: '1:936537359592:web:81bc75feae7d8ad715355d',
    messagingSenderId: '936537359592',
    projectId: 'gdrm-userbase',
    authDomain: 'gdrm-userbase.firebaseapp.com',
    storageBucket: 'gdrm-userbase.firebasestorage.app',
    measurementId: 'G-3Q2GGW2HK6',
  );
}
