import 'dart:io';

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'firebase_options.dart'; // Auto-generated by running `flutterfire configure`
import 'package:gdrm_ecosystem/screens/home_screen.dart';
import 'package:gdrm_ecosystem/services/file_intent_service.dart';
import 'package:gdrm_ecosystem/services/security_service.dart';
import 'package:gdrm_ecosystem/state/app_state.dart';
import 'package:gdrm_ecosystem/theme/app_theme.dart';

void main(List<String> args) async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Initialize Firebase Ecosystem ─────────────────────────────────────────
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Apply screenshot prevention + Windows file association
  await SecurityService.init();

  // Start listening for incoming file intents / CLI args
  await FileIntentService.init(args);

  runApp(const GDRMApp());
}

class GDRMApp extends StatelessWidget {
  const GDRMApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => AppState(),
      child: MaterialApp(
        title: 'GDRM Ecosystem',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.darkTheme,
        home: const HomeScreen(),
      ),
    );
  }
}